ProxyPreserveHost On
ProxyAddHeaders On
RedirectMatch 302 ^/admin$ /admin/
ProxyPass /admin/ http://127.0.0.1:8093/ retry=0 timeout=30
ProxyPassReverse /admin/ http://127.0.0.1:8093/
ProxyPass / http://127.0.0.1:8092/ retry=0 timeout=190
ProxyPassReverse / http://127.0.0.1:8092/
RequestHeader set X-Forwarded-Proto "https"
