#!/usr/bin/env python3
import argparse, copy, email, fnmatch, hashlib, html, json, mailbox, os, re, sqlite3, subprocess, tempfile, urllib.parse, zipfile
from datetime import datetime, timezone
from email.header import decode_header, make_header
from email.utils import parsedate_to_datetime
from collections import Counter, defaultdict
from html.parser import HTMLParser
from pathlib import Path
from github_connector import load_cached_repository
from html_manual_connector import load_cached_manual
from owned_images import create_image_schema,export_help_images,store_page_images

BUILDER_VERSION='0.20'

class Parser(HTMLParser):
    SKIP_TAGS={'script','style','noscript','template'}

    def __init__(self):
        super().__init__(); self.text=[]; self.links=[]; self.images=[]; self.image_details=[]; self.title=[]; self._in_title=False; self._skip_depth=0; self.ids=set(); self.keywords=[]
    def handle_starttag(self, tag, attrs):
        tag=tag.lower()
        if tag in self.SKIP_TAGS:
            self._skip_depth+=1
            return
        if self._skip_depth:
            return
        a=dict(attrs)
        if tag=='title': self._in_title=True
        if tag=='a' and a.get('href'): self.links.append(a['href'])
        if tag=='img' and a.get('src'):
            self.images.append(a['src'])
            self.image_details.append({
                'src':a['src'],'alt':a.get('alt',''),'title':a.get('title',''),
                'width':a.get('width',''),'height':a.get('height',''),
            })
        if a.get('id'): self.ids.add(a['id'])
        if a.get('name'): self.ids.add(a['name'])
        if tag=='meta' and a.get('name','').lower()=='keywords': self.keywords += [x.strip() for x in a.get('content','').split(',') if x.strip()]
    def handle_endtag(self, tag):
        tag=tag.lower()
        if tag in self.SKIP_TAGS:
            self._skip_depth=max(0,self._skip_depth-1)
            return
        if self._skip_depth:
            return
        if tag=='title': self._in_title=False
    def handle_data(self, data):
        if self._skip_depth:
            return
        s=' '.join(data.split())
        if s:
            self.text.append(s)
            if self._in_title: self.title.append(s)

def deep_merge(base, override):
    result=copy.deepcopy(base)
    for key,value in override.items():
        if isinstance(value,dict) and isinstance(result.get(key),dict):
            result[key]=deep_merge(result[key],value)
        else:
            result[key]=copy.deepcopy(value)
    return result

def load_json(path):
    with open(path,encoding='utf-8') as f:
        data=json.load(f)
    if not isinstance(data,dict):
        raise ValueError(f'Configuration file must contain a JSON object: {path}')
    return data

def load_cfg(path):
    path=Path(path)
    cfg=load_json(path)
    base=path.parent
    includes=cfg.pop('include',[])
    if isinstance(includes,str): includes=[includes]
    merged={}
    for item in includes:
        inc=Path(item)
        if not inc.is_absolute(): inc=base/inc
        merged=deep_merge(merged,load_json(inc))
    cfg=deep_merge(merged,cfg)
    project=cfg.setdefault('project',{})
    project.setdefault('product_name','My Product')
    project.setdefault('help_name','Assistant')
    project.setdefault('builder_name','Documentation Knowledge Builder')
    project.setdefault('report_title',f"{project['product_name']} Documentation QA")
    project.setdefault('version',BUILDER_VERSION)
    cfg.setdefault('paths',{}).setdefault('output_directory','output')
    cfg['paths'].setdefault('database_name','knowledge.db')
    cfg.setdefault('report',{})
    cfg['report'].setdefault('generate_html',True)
    cfg['report'].setdefault('generate_json',True)
    cfg['report'].setdefault('generate_sqlite',True)
    cfg['report'].setdefault('generate_build_report',True)
    messages=cfg.setdefault('messages',{})
    help_name=project.get('help_name','Assistant')
    messages.setdefault('report_subtitle','{product_name} — generated by {builder_name} v{version}')
    messages.setdefault('report_closing',f'73 from {help_name}!')
    messages.setdefault('console_closing',messages['report_closing'])
    messages.setdefault('build_complete','Help topics: {topics}  Quality: {overall_quality}%  Broken internal links: {broken_internal_links}  Missing images: {missing_images}')
    cfg.setdefault('help',{})
    cfg['help'].setdefault('home_page','index.html')
    cfg['help'].setdefault('minimum_page_words',100)
    cfg['help'].setdefault('exclude_files',[])
    cfg['help'].setdefault('exclude_directories',[])
    cfg['help'].setdefault('html_extensions',['.html','.htm'])
    cfg.setdefault('link_check',{}).setdefault('ignored_patterns',[])
    cfg['link_check'].setdefault('review_patterns',[])
    cfg.setdefault('analysis',{}).setdefault('legacy_terms',[])
    cfg['analysis'].setdefault('report_unused_images',True)
    cfg['analysis'].setdefault('report_orphan_pages',True)
    cfg['analysis'].setdefault('knowledge_analysis',{})
    ka=cfg['analysis']['knowledge_analysis']
    ka.setdefault('enabled',True)
    ka.setdefault('top_topics',25)
    ka.setdefault('top_threads',20)
    ka.setdefault('minimum_topic_length',3)
    ka.setdefault('stop_words',['the','and','for','that','this','with','from','have','your','you','are','was','were','but','not','can','how','what','when','where','who','why','re','fw','fwd','rigpi','help','question','problem'])
    ka.setdefault('gap_minimum_messages',5)
    # v0.18 calls configured inputs connectors. Older sources arrays remain valid.
    connectors=cfg.get('connectors')
    sources=cfg.get('sources')
    if connectors is None and sources is None:
        connectors=[]
    elif connectors is None:
        connectors=sources
    elif sources:
        known={str(x.get('id','')) for x in connectors if isinstance(x,dict)}
        connectors=list(connectors)+[x for x in sources if isinstance(x,dict) and str(x.get('id','')) not in known]
    if not isinstance(connectors,list):
        raise ValueError('connectors must be a JSON array')
    seen=set()
    for i,item in enumerate(connectors):
        if not isinstance(item,dict):
            raise ValueError(f'connector #{i+1} must be a JSON object')
        cid=str(item.get('id','')).strip()
        ctype=str(item.get('type','')).strip()
        if not cid or not ctype:
            raise ValueError(f'connector #{i+1} requires id and type')
        if cid in seen:
            raise ValueError(f'duplicate connector id: {cid}')
        seen.add(cid)
        item.setdefault('name',cid)
        item.setdefault('enabled',False)
        item.setdefault('authority',50)
        item.setdefault('category','reference')
        item.setdefault('tags',[])
        item.setdefault('refresh','manual')
        item.setdefault('options',{})
    cfg['connectors']=connectors
    cfg['sources']=connectors  # compatibility alias used by the v0.17 engine
    return cfg


def decode_mime(value):
    if not value:
        return ''
    try:
        return str(make_header(decode_header(str(value))))
    except Exception:
        return str(value)

def message_text(msg):
    if msg.get_content_disposition()=='attachment':
        return ''
    if msg.is_multipart():
        children=msg.get_payload()
        if not isinstance(children,list):
            children=[]
        if msg.get_content_subtype().lower()=='alternative':
            # The alternatives are equivalent representations. Prefer plain
            # text so the same message is not indexed once as text and again
            # as HTML.
            for wanted in ('text/plain','text/html'):
                for part in children:
                    if part.get_content_type()==wanted and part.get_content_disposition()!='attachment':
                        text=message_text(part)
                        if text.strip(): return text
            return next((text for part in children if (text:=message_text(part)).strip()),'')
        return '\n'.join(text for part in children if (text:=message_text(part)).strip())
    if msg.get_content_type() not in ('text/plain','text/html'):
        return ''
    try:
        payload=msg.get_payload(decode=True)
        charset=msg.get_content_charset() or 'utf-8'
        text=payload.decode(charset,errors='replace') if isinstance(payload,(bytes,bytearray)) else str(payload or '')
    except Exception:
        text=str(msg.get_payload() or '')
    if msg.get_content_type()=='text/html':
        hp=Parser(); hp.feed(text); text='\n'.join(hp.text)
    return text

def normalize_subject(subject):
    subject=decode_mime(subject).strip()
    old=None
    while subject!=old:
        old=subject
        subject=re.sub(r'^\s*((re|fw|fwd)\s*:\s*)+','',subject,flags=re.I)
        subject=re.sub(r'^\s*\[[^\]]+\]\s*','',subject)
    return re.sub(r'\s+',' ',subject).strip() or '(no subject)'

def strip_quoted(text):
    lines=[]
    for line in text.splitlines():
        if re.match(r'^\s*>',line):
            continue
        if re.match(r'^\s*On .+ wrote:\s*$',line,re.I):
            break
        lines.append(line)
    return '\n'.join(lines)

def strip_signature(text):
    lines=text.splitlines()
    for i,line in enumerate(lines):
        if line.strip()=='--':
            return '\n'.join(lines[:i])
    return text

def strip_groups_footer(text):
    patterns=[r'^_+\s*$',r'^Groups\.io Links:',r'^You receive all messages sent to this group\.',r'^View/Reply Online']
    lines=[]
    for line in text.splitlines():
        if any(re.search(p,line,re.I) for p in patterns):
            break
        lines.append(line)
    return '\n'.join(lines)

def clean_message_body(text,opts):
    text=text.replace('\r\n','\n').replace('\r','\n')
    if opts.get('strip_quoted_replies',True): text=strip_quoted(text)
    if opts.get('strip_signatures',True): text=strip_signature(text)
    if opts.get('strip_groups_footer',True): text=strip_groups_footer(text)
    text='\n'.join(line.rstrip() for line in text.splitlines())
    text=re.sub(r'\n{3,}','\n\n',text).strip()
    return text

def parse_date(value):
    try:
        d=parsedate_to_datetime(value)
        if d.tzinfo is None: d=d.replace(tzinfo=timezone.utc)
        return d.astimezone(timezone.utc).isoformat()
    except Exception:
        return ''

def import_groups_mbox(path,source_cfg):
    opts=source_cfg.get('options',{})
    # Connector identity may live beside the common connector fields or in
    # options for compatibility with older modular configurations.
    base_url=str(source_cfg.get('base_url') or opts.get('base_url','')).rstrip('/')
    minimum=int(opts.get('minimum_message_words',5))
    dedupe=bool(opts.get('deduplicate_messages',True))
    seen=set(); messages=[]; duplicates=0; empty=0
    box=mailbox.mbox(path,create=False)
    for seq,msg in enumerate(box,1):
        subject=decode_mime(msg.get('subject',''))
        thread_subject=normalize_subject(subject)
        author=decode_mime(msg.get('from',''))
        date=parse_date(msg.get('date',''))
        message_id=str(msg.get('message-id','')).strip()
        in_reply_to=str(msg.get('in-reply-to','')).strip()
        refs=str(msg.get('references','')).strip()
        groupsio_msgnum=str(msg.get('X-Groupsio-MsgNum','')).strip()
        if not groupsio_msgnum.isdigit(): groupsio_msgnum=''
        source_url=f'{base_url}/message/{groupsio_msgnum}' if base_url and groupsio_msgnum else ''
        body=clean_message_body(message_text(msg),opts)
        words=len(re.findall(r"\b[\w'-]+\b",body))
        if words<minimum:
            empty+=1; continue
        key=message_id or hashlib.sha256((author+'\n'+date+'\n'+thread_subject+'\n'+body).encode('utf-8','replace')).hexdigest()
        if dedupe and key in seen:
            duplicates+=1; continue
        seen.add(key)
        messages.append({'sequence':seq,'message_id':message_id,'in_reply_to':in_reply_to,'references':refs,'groupsio_msgnum':groupsio_msgnum,'source_url':source_url,'subject':subject or thread_subject,'thread_subject':thread_subject,'author':author,'date':date,'body':body,'words':words})
    threads={}
    for m in messages:
        key=m['thread_subject'].casefold()
        t=threads.setdefault(key,{'thread_id':'','subject':m['thread_subject'],'message_count':0,'first_date':'','last_date':'','authors':set(),'messages':[]})
        t['messages'].append(m); t['message_count']+=1
        if m['author']: t['authors'].add(m['author'])
        if m['date']:
            if not t['first_date'] or m['date']<t['first_date']: t['first_date']=m['date']
            if not t['last_date'] or m['date']>t['last_date']: t['last_date']=m['date']
    out=[]
    source_prefix=re.sub(r'[^A-Za-z0-9]+','-',source_cfg.get('id','groups-messages')).strip('-').upper() or 'GROUPS'
    for i,t in enumerate(sorted(threads.values(),key=lambda x:(x['first_date'],x['subject'])),1):
        t['thread_id']=f"{source_prefix}-THREAD-{i:05d}"; t['authors']=sorted(t['authors']); out.append(t)
        for j,m in enumerate(t['messages'],1):
            m['stable_id']=f"{t['thread_id']}-MSG-{j:04d}"
            m['thread_id']=t['thread_id']
            m['local_ref']='elmer://source/{}/thread/{}/message/{}'.format(
                urllib.parse.quote(source_cfg.get('id','groups-messages'),safe=''),
                urllib.parse.quote(m['thread_id'],safe=''),
                urllib.parse.quote(m['stable_id'],safe=''))
    dates=[m['date'] for m in messages if m['date']]
    summary={'messages':len(messages),'threads':len(out),'contributors':len({m['author'] for m in messages if m['author']}),'duplicates':duplicates,'empty_or_short':empty,'date_start':min(dates) if dates else '','date_end':max(dates) if dates else '','average_thread_size':round(len(messages)/max(1,len(out)),2)}
    return {'source_id':source_cfg.get('id','groups-messages'),'name':source_cfg.get('name',source_cfg.get('id','groups-messages')),'tags':source_cfg.get('tags',[]),'source_type':'groups_io_mbox','authority':int(source_cfg.get('authority',60)),'path':str(path),'summary':summary,'threads':out,'messages':messages}

def extract_docx_text(path):
    parts=[]
    with zipfile.ZipFile(path) as archive:
        names=['word/document.xml']+sorted(n for n in archive.namelist() if re.match(r'word/(header|footer)\d+\.xml$',n))
        for name in names:
            if name not in archive.namelist(): continue
            raw=archive.read(name).decode('utf-8',errors='replace')
            raw=re.sub(r'</w:(p|tr)>','\n',raw)
            text=html.unescape(re.sub(r'<[^>]+>',' ',raw))
            parts.append(text)
    return '\n'.join(parts)

def extract_rtf_text(path):
    raw=path.read_bytes().decode('latin-1',errors='replace')
    raw=re.sub(r"\\'[0-9a-fA-F]{2}",lambda m:bytes([int(m.group()[2:],16)]).decode('cp1252',errors='replace'),raw)
    raw=re.sub(r'\\(par|line)\b\s*','\n',raw)
    raw=re.sub(r'\\[a-zA-Z]+-?\d*\s?',' ',raw)
    raw=re.sub(r'\\[^a-zA-Z]',' ',raw)
    return raw.replace('{',' ').replace('}',' ')

def extract_groups_file_text(path):
    ext=path.suffix.lower()
    if ext=='.pdf':
        try:
            result=subprocess.run(['pdftotext','-layout',str(path),'-'],capture_output=True,timeout=120)
        except (FileNotFoundError,subprocess.TimeoutExpired):
            return ''
        return result.stdout.decode('utf-8',errors='replace') if result.returncode==0 else ''
    if ext=='.docx':
        try: return extract_docx_text(path)
        except (OSError,KeyError,zipfile.BadZipFile): return ''
    if ext=='.rtf': return extract_rtf_text(path)
    data=path.read_bytes()
    if b'\x00' in data: return ''
    return data.decode('utf-8',errors='replace')

def normalize_extracted_text(text):
    text=text.replace('\r\n','\n').replace('\r','\n')
    text='\n'.join(re.sub(r'[ \t]+',' ',line).strip() for line in text.splitlines())
    return re.sub(r'\n{3,}','\n\n',text).strip()

def import_groups_files(path,source_cfg):
    path=Path(path)
    if path.is_file() and zipfile.is_zipfile(path):
        with tempfile.TemporaryDirectory(prefix='elmer-groups-files-') as td:
            with zipfile.ZipFile(path) as archive: archive.extractall(td)
            report=import_groups_files(Path(td),source_cfg)
            report['path']=str(path)
            return report
    root=path/'Files' if (path/'Files').is_dir() else path
    opts=source_cfg.get('options',{})
    allowed={str(x).lower() for x in opts.get('extensions',['.pdf','.docx','.rtf','.txt','.dat','.h','.md'])}
    base_url=str(source_cfg.get('base_url') or opts.get('base_url','')).rstrip('/')
    minimum=int(opts.get('minimum_document_words',3))
    prefix=re.sub(r'[^A-Za-z0-9]+','-',source_cfg.get('id','groups-files')).strip('-').upper() or 'GROUPS-FILES'
    documents=[]; seen_hashes={}; duplicates=[]; unsupported=0; failed=0
    candidates=[p for p in root.rglob('*') if p.is_file() and not p.name.endswith('.json') and not is_archive_artifact(p.relative_to(root))]
    # Prefer the copy carrying Groups.io metadata when identical files occur
    # in multiple folders, so the retained document has the stable export ID.
    candidates.sort(key=lambda p:(not Path(str(p)+'.json').exists(),p.relative_to(root).as_posix()))
    for file_path in candidates:
        if file_path.suffix.lower() not in allowed:
            unsupported+=1; continue
        raw_hash=hashlib.sha256(file_path.read_bytes()).hexdigest()
        rel=file_path.relative_to(root).as_posix()
        if raw_hash in seen_hashes:
            duplicates.append({'path':rel,'duplicate_of':seen_hashes[raw_hash]}); continue
        metadata={}; sidecar=Path(str(file_path)+'.json')
        if sidecar.exists():
            try:
                candidate=json.loads(sidecar.read_text(encoding='utf-8'))
                if isinstance(candidate,dict) and candidate.get('object')=='file': metadata=candidate
            except (OSError,json.JSONDecodeError): pass
        text=normalize_extracted_text(extract_groups_file_text(file_path))
        description=normalize_extracted_text(str(metadata.get('desc') or ''))
        body='\n\n'.join(x for x in (description,text) if x)
        words=len(re.findall(r"\b[\w'-]+\b",body))
        if words<minimum:
            failed+=1; continue
        seen_hashes[raw_hash]=rel
        file_id=str(metadata.get('id') or '')
        sid=f'{prefix}-FILE-{file_id}' if file_id.isdigit() else f'{prefix}-FILE-{hashlib.sha256(rel.encode()).hexdigest()[:16].upper()}'
        original=str(metadata.get('path') or rel).replace('\\','/')
        marker='/Files/'
        public_path=original.split(marker,1)[1] if marker in original else rel
        source_url=f'{base_url}/files/{urllib.parse.quote(public_path,safe="/")}' if base_url else ''
        local='elmer://source/{}/document/{}'.format(urllib.parse.quote(source_cfg.get('id','groups-files'),safe=''),urllib.parse.quote(sid,safe=''))
        documents.append({'stable_id':sid,'title':str(metadata.get('name') or file_path.name),'path':rel,'source_type':'groups_io_file','authority':int(source_cfg.get('authority',70)),'words':words,'author':'','published_at':str(metadata.get('updated') or metadata.get('created') or ''),'thread_id':'','source_url':source_url,'local_ref':local,'body':body})
    by_extension=dict(sorted(Counter(Path(d['path']).suffix.lower() or '(none)' for d in documents).items()))
    summary={'documents':len(documents),'duplicates':len(duplicates),'unsupported':unsupported,'extraction_failed_or_short':failed,'by_extension':by_extension}
    return {'source_id':source_cfg.get('id','groups-files'),'name':source_cfg.get('name',source_cfg.get('id','groups-files')),'tags':source_cfg.get('tags',[]),'source_type':'groups_io_files','authority':int(source_cfg.get('authority',70)),'path':str(path),'summary':summary,'documents':documents,'duplicates':duplicates}

def source_inventory(cfg,base):
    rows=[]
    for s in cfg.get('sources',[]):
        path=resolve(base,s.get('path','')) if s.get('path') else None
        if s.get('type')=='github_repository':
            cache=resolve(base,cfg.get('paths',{}).get('connector_cache_directory','cache/connectors'))/str(s.get('id',''))/'manifest.json'
            exists=cache.exists()
        else: exists=bool(path and path.exists())
        rows.append({'id':s.get('id',''),'type':s.get('type',''),'enabled':bool(s.get('enabled')),'authority':int(s.get('authority',0)),'path':str(path) if path else '','exists':exists})
    return rows

def resolve(base,p):
    q=Path(p); return q if q.is_absolute() else (base/q)
def is_archive_artifact(path):
    """Return true for platform metadata that is not knowledge content."""
    return any(part=='__MACOSX' or part=='.DS_Store' or part.startswith('._') for part in Path(path).parts)
def matches(value, patterns): return next((p for p in patterns if fnmatch.fnmatch(value,p)), None)
def source(cfg, typ): return next((s for s in cfg.get('sources',[]) if s.get('enabled') and s.get('type')==typ), None)
def clean_target(href):
    return urllib.parse.unquote(href.split('?',1)[0])
def page_score(p, min_words):
    score=100
    if p['words']<min_words: score-=20
    if p['missing_images']: score-=25
    if p['broken_internal']: score-=25
    if p['legacy_hits']: score-=10
    if not p['title']: score-=10
    if not p['keywords']: score-=5
    return max(0,score)
def stars(score): return '★'*(max(1,round(score/20)))+'☆'*(5-max(1,round(score/20)))

def analyze(root,cfg):
    hc=cfg['help']; ac=cfg['analysis']; lc=cfg['link_check']
    exfiles=set(hc.get('exclude_files',[])); exdirs=set(hc.get('exclude_directories',[])); exts=tuple(hc.get('html_extensions',['.html','.htm']))
    files=[]
    for p in root.rglob('*'):
        rel=p.relative_to(root).as_posix()
        if is_archive_artifact(p.relative_to(root)): continue
        if any(part in exdirs for part in p.relative_to(root).parts): continue
        if p.is_file() and p.suffix.lower() in exts and p.name not in exfiles: files.append(p)
    relmap={p.relative_to(root).as_posix():p for p in files}; pages=[]; incoming=Counter(); all_images=set(); used_images=set(); titles=defaultdict(list); keyword_pages=defaultdict(list)
    for p in files:
        rel=p.relative_to(root).as_posix(); raw=p.read_text(encoding='utf-8',errors='replace'); hp=Parser(); hp.feed(raw)
        text=' '.join(hp.text); title=' '.join(hp.title).strip(); words=len(re.findall(r"\b[\w'-]+\b",text))
        titles[title].append(rel) if title else None
        for k in hp.keywords: keyword_pages[k.lower()].append(rel)
        missing_images=[]
        for src in hp.images:
            if urllib.parse.urlparse(src).scheme or src.startswith('//'): continue
            target=(p.parent/clean_target(src)).resolve()
            try: tr=target.relative_to(root.resolve()).as_posix()
            except Exception: tr=clean_target(src)
            used_images.add(tr)
            if not target.exists(): missing_images.append(src)
        broken=[]; missing_anchors=[]; external=[]; ignored=[]; review=[]
        for href in hp.links:
            ig=matches(href,lc.get('ignored_patterns',[]))
            if ig: ignored.append({'url':href,'pattern':ig}); continue
            rv=matches(href,lc.get('review_patterns',[]))
            if rv: review.append({'url':href,'pattern':rv}); continue
            u=urllib.parse.urlparse(href)
            if u.scheme in ('http','https'): external.append(href); continue
            if u.scheme: continue
            pathpart=clean_target(href).split('#',1)[0]; anchor=href.split('#',1)[1] if '#' in href else ''
            if not pathpart:
                target_rel=rel
            else:
                target_abs=(p.parent/pathpart).resolve()
                try: target_rel=target_abs.relative_to(root.resolve()).as_posix()
                except Exception: target_rel=pathpart
            if target_rel.lower().endswith(exts):
                if target_rel not in relmap: broken.append(href)
                else:
                    incoming[target_rel]+=1
                    if anchor:
                        tp=Parser(); tp.feed(relmap[target_rel].read_text(encoding='utf-8',errors='replace'))
                        if anchor not in tp.ids: missing_anchors.append(href)
        legacy=[]
        for term in ac.get('legacy_terms',[]):
            n=len(re.findall(re.escape(term),text,re.I))
            if n: legacy.append({'term':term,'count':n})
        entry={'file':rel,'title':title,'words':words,'images':len(hp.images),'image_details':hp.image_details,'internal_links':len(hp.links)-len(external),'external_links':len(external),'keywords':hp.keywords,'missing_images':missing_images,'broken_internal':broken,'missing_anchors':missing_anchors,'external_urls':external,'ignored_urls':ignored,'review_urls':review,'legacy_hits':legacy,'text':text}
        entry['score']=page_score(entry,hc.get('minimum_page_words',100)); entry['stars']=stars(entry['score']); pages.append(entry)
    for p in root.rglob('*'):
        if not is_archive_artifact(p.relative_to(root)) and p.is_file() and p.suffix.lower() in ('.png','.jpg','.jpeg','.gif','.svg','.webp'):
            all_images.add(p.relative_to(root).as_posix())
    home=hc.get('home_page','index.html')
    orphans=[p['file'] for p in pages if incoming[p['file']]==0 and p['file']!=home]
    duplicates={k:v for k,v in titles.items() if k and len(v)>1}
    duplicate_keywords={k:v for k,v in keyword_pages.items() if len(v)>1}
    unused=sorted(all_images-used_images)
    summary={'topics':len(pages),'images':len(all_images),'internal_links':sum(p['internal_links'] for p in pages),'external_links':sum(p['external_links'] for p in pages),'broken_internal_links':sum(len(p['broken_internal']) for p in pages),'missing_anchors':sum(len(p['missing_anchors']) for p in pages),'missing_images':sum(len(p['missing_images']) for p in pages),'unused_images':len(unused),'orphan_pages':len(orphans),'duplicate_titles':len(duplicates),'legacy_references':sum(sum(x['count'] for x in p['legacy_hits']) for p in pages),'ignored_urls':sum(len(p['ignored_urls']) for p in pages),'needs_review_urls':sum(len(p['review_urls']) for p in pages),'average_words':round(sum(p['words'] for p in pages)/max(1,len(pages)),1),'overall_quality':round(sum(p['score'] for p in pages)/max(1,len(pages)),1)}
    return {'summary':summary,'pages':pages,'orphans':orphans,'duplicate_titles':duplicates,'duplicate_keywords':duplicate_keywords,'unused_images':unused}


def analyze_knowledge(help_report, groups_reports, cfg):
    opts=cfg.get('analysis',{}).get('knowledge_analysis',{})
    if not opts.get('enabled',True):
        return {'enabled':False,'top_topics':[],'top_threads':[],'coverage_gaps':[],'recommendations':[],'promotion_candidates':[],'source_intelligence':[]}
    stop={str(x).casefold() for x in opts.get('stop_words',[])}
    min_len=int(opts.get('minimum_topic_length',3))
    token_re=re.compile(r"[A-Za-z0-9][A-Za-z0-9+._/-]*")
    forum=Counter(); help_counts=Counter(); examples=defaultdict(list); per_source=defaultdict(Counter)
    def tokens(text):
        for raw in token_re.findall(text or ''):
            t=raw.casefold().strip('._-/')
            if len(t)>=min_len and t not in stop and not t.isdigit():
                yield t
    for page in help_report.get('pages',[]):
        weighted=' '.join([page.get('title','')]*5 + page.get('keywords',[]) + [page.get('text','')])
        help_counts.update(set(tokens(weighted)))
    all_threads=[]
    source_intelligence=[]
    for gr in groups_reports or []:
        for t in gr.get('threads',[]):
            all_threads.append({'source_id':gr['source_id'],'thread_id':t['thread_id'],'subject':t['subject'],'message_count':t['message_count'],'authors':len(t.get('authors',[])),'first_date':t.get('first_date',''),'last_date':t.get('last_date','')})
        for m in gr.get('messages',[]):
            terms=set(tokens(m.get('thread_subject','')))
            forum.update(terms); per_source[gr['source_id']].update(terms)
            for term in terms:
                if len(examples[term])<3 and m.get('thread_subject','') not in examples[term]: examples[term].append(m.get('thread_subject',''))
        source_intelligence.append({'source_id':gr['source_id'],'name':gr.get('name',gr['source_id']),'authority':gr['authority'],'messages':gr['summary']['messages'],'threads':gr['summary']['threads'],'contributors':gr['summary']['contributors'],'date_start':gr['summary']['date_start'],'date_end':gr['summary']['date_end'],'tags':gr.get('tags',[])})
    top_topics=[]
    for term,count in forum.most_common(int(opts.get('top_topics',25))):
        top_topics.append({'topic':term,'forum_messages':count,'help_pages':help_counts.get(term,0),'examples':examples[term],'sources':{sid:c.get(term,0) for sid,c in per_source.items() if c.get(term,0)}})
    min_msgs=int(opts.get('gap_minimum_messages',5))
    gaps=[{'topic':term,'forum_messages':count,'help_pages':help_counts.get(term,0),'examples':examples[term],'sources':{sid:c.get(term,0) for sid,c in per_source.items() if c.get(term,0)}} for term,count in forum.items() if count>=min_msgs and help_counts.get(term,0)==0]
    gaps=sorted(gaps,key=lambda x:(-x['forum_messages'],x['topic']))[:int(opts.get('top_topics',25))]
    recs=[]
    max_count=max([x['forum_messages'] for x in gaps],default=1)
    for rank,x in enumerate(gaps,1):
        source_bonus=min(15,max(0,(len(x['sources'])-1)*8))
        confidence=min(99,round(45+45*x['forum_messages']/max_count+source_bonus))
        impact='Very High' if confidence>=90 else 'High' if confidence>=75 else 'Medium' if confidence>=60 else 'Review'
        recs.append({**x,'rank':rank,'confidence':confidence,'impact':impact,'recommendation':f"Create or expand a Help topic for {x['topic']}."})
    promotions=[x for x in recs if len(x['sources'])>=2 or x['confidence']>=80]
    top_threads=sorted(all_threads,key=lambda x:(-x['message_count'],x['subject'].casefold()))[:int(opts.get('top_threads',20))]
    return {'enabled':True,'top_topics':top_topics,'top_threads':top_threads,'coverage_gaps':gaps,'recommendations':recs,'promotion_candidates':promotions,'source_intelligence':source_intelligence,'topics_analyzed':len(forum)}

def write_db(path,report,cfg,groups_reports=None,github_reports=None,file_reports=None):
    if path.exists(): path.unlink()
    db=sqlite3.connect(path)
    db.executescript('''
    CREATE TABLE sources(id TEXT PRIMARY KEY,type TEXT,path TEXT,authority INTEGER,enabled INTEGER,document_count INTEGER,updated_at TEXT);
    CREATE TABLE documents(id INTEGER PRIMARY KEY,stable_id TEXT UNIQUE,title TEXT,path TEXT,source_id TEXT,source_type TEXT,authority INTEGER,word_count INTEGER,quality_score INTEGER,author TEXT,published_at TEXT,thread_id TEXT,source_url TEXT,local_ref TEXT);
    CREATE TABLE threads(thread_id TEXT PRIMARY KEY,source_id TEXT,subject TEXT,message_count INTEGER,first_date TEXT,last_date TEXT,authors_json TEXT);
    CREATE TABLE messages(stable_id TEXT PRIMARY KEY,thread_id TEXT,source_id TEXT,message_id TEXT,groupsio_msgnum TEXT,subject TEXT,author TEXT,published_at TEXT,word_count INTEGER,body TEXT,source_url TEXT,local_ref TEXT);
    CREATE VIRTUAL TABLE chunks USING fts5(stable_id,title,path,content,source_id,source_type,author,thread_id,source_url UNINDEXED,local_ref UNINDEXED);
    ''')
    create_image_schema(db)
    now=datetime.now(timezone.utc).isoformat()
    help_source=next((x for x in cfg.get('sources',[]) if x.get('type')=='help_zip' and x.get('enabled')),{'id':'official-help','path':'','authority':100})
    image_records={
        item['image_id']:item
        for item in report.get('owned_images_manifest',{}).get('images',[])
    }
    db.execute('INSERT OR REPLACE INTO sources VALUES(?,?,?,?,?,?,?)',(help_source.get('id','official-help'),'help_zip',help_source.get('path',''),int(help_source.get('authority',100)),1,len(report['pages']),now))
    for i,p in enumerate(report['pages'],1):
        sid=f"HELP-{i:04d}"; text=p.get('text','')
        source_id=help_source.get('id','official-help')
        local='elmer://source/{}/document/{}'.format(urllib.parse.quote(source_id,safe=''),urllib.parse.quote(sid,safe=''))
        db.execute('INSERT INTO documents(stable_id,title,path,source_id,source_type,authority,word_count,quality_score,author,published_at,thread_id,source_url,local_ref) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)',(sid,p['title'],p['file'],source_id,'help',int(help_source.get('authority',100)),p['words'],p['score'],'','','','',local))
        store_page_images(db,p,sid,image_records)
        for off in range(0,len(text),1200): db.execute('INSERT INTO chunks VALUES(?,?,?,?,?,?,?,?,?,?)',(sid,p['title'],p['file'],text[off:off+1200],source_id,'help','','','',local))
    for gr in groups_reports or []:
        db.execute('INSERT OR REPLACE INTO sources VALUES(?,?,?,?,?,?,?)',(gr['source_id'],gr['source_type'],gr['path'],gr['authority'],1,gr['summary']['messages'],now))
        for t in gr['threads']:
            db.execute('INSERT INTO threads VALUES(?,?,?,?,?,?,?)',(t['thread_id'],gr['source_id'],t['subject'],t['message_count'],t['first_date'],t['last_date'],json.dumps(t['authors'])))
        for m in gr['messages']:
            path=f"thread:{m['thread_subject']}"
            db.execute('INSERT INTO documents(stable_id,title,path,source_id,source_type,authority,word_count,quality_score,author,published_at,thread_id,source_url,local_ref) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)',(m['stable_id'],m['subject'],path,gr['source_id'],'groups_io_message',gr['authority'],m['words'],None,m['author'],m['date'],m['thread_id'],m['source_url'],m['local_ref']))
            tid=m['thread_id']
            db.execute('INSERT INTO messages VALUES(?,?,?,?,?,?,?,?,?,?,?,?)',(m['stable_id'],tid,gr['source_id'],m['message_id'],m['groupsio_msgnum'],m['subject'],m['author'],m['date'],m['words'],m['body'],m['source_url'],m['local_ref']))
            for off in range(0,len(m['body']),1200): db.execute('INSERT INTO chunks VALUES(?,?,?,?,?,?,?,?,?,?)',(m['stable_id'],m['subject'],path,m['body'][off:off+1200],gr['source_id'],'groups_io_message',m['author'],tid,m['source_url'],m['local_ref']))
    for gr in github_reports or []:
        db.execute('INSERT OR REPLACE INTO sources VALUES(?,?,?,?,?,?,?)',(gr['source_id'],gr['source_type'],gr['path'],gr['authority'],1,len(gr['documents']),now))
        for d in gr['documents']:
            db.execute('INSERT INTO documents(stable_id,title,path,source_id,source_type,authority,word_count,quality_score,author,published_at,thread_id,source_url,local_ref) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)',(d['stable_id'],d['title'],d['path'],gr['source_id'],d['source_type'],d['authority'],d['words'],None,d['author'],d['published_at'],d['thread_id'],d['source_url'],d['local_ref']))
            for off in range(0,len(d['body']),1200): db.execute('INSERT INTO chunks VALUES(?,?,?,?,?,?,?,?,?,?)',(d['stable_id'],d['title'],d['path'],d['body'][off:off+1200],gr['source_id'],d['source_type'],d['author'],d['thread_id'],d['source_url'],d['local_ref']))
    for gr in file_reports or []:
        db.execute('INSERT OR REPLACE INTO sources VALUES(?,?,?,?,?,?,?)',(gr['source_id'],gr['source_type'],gr['path'],gr['authority'],1,len(gr['documents']),now))
        for d in gr['documents']:
            db.execute('INSERT INTO documents(stable_id,title,path,source_id,source_type,authority,word_count,quality_score,author,published_at,thread_id,source_url,local_ref) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)',(d['stable_id'],d['title'],d['path'],gr['source_id'],d['source_type'],d['authority'],d['words'],None,d['author'],d['published_at'],d['thread_id'],d['source_url'],d['local_ref']))
            for off in range(0,len(d['body']),1200): db.execute('INSERT INTO chunks VALUES(?,?,?,?,?,?,?,?,?,?)',(d['stable_id'],d['title'],d['path'],d['body'][off:off+1200],gr['source_id'],d['source_type'],d['author'],d['thread_id'],d['source_url'],d['local_ref']))
    db.commit(); db.close()

def format_message(template,cfg,summary=None):
    values={}
    values.update(cfg.get('project',{}))
    if summary: values.update(summary)
    try:
        return str(template).format_map(defaultdict(str,values))
    except (ValueError,KeyError):
        return str(template)

def html_report(report,cfg,groups_reports=None,inventory=None):
    s=report['summary']; title=html.escape(cfg['project']['report_title'])
    subtitle=format_message(cfg.get('messages',{}).get('report_subtitle',''),cfg,s)
    closing=format_message(cfg.get('messages',{}).get('report_closing',''),cfg,s)
    rows=''.join(f"<tr><td>{html.escape(p['title'] or '(untitled)')}</td><td>{html.escape(p['file'])}</td><td>{p['words']}</td><td>{p['stars']} {p['score']}%</td><td>{len(p['broken_internal'])}</td><td>{len(p['missing_images'])}</td><td>{sum(x['count'] for x in p['legacy_hits'])}</td></tr>" for p in sorted(report['pages'],key=lambda x:x['score']))
    cards=''.join(f"<div class=card><b>{html.escape(k.replace('_',' ').title())}</b><span>{v}</span></div>" for k,v in s.items())
    def lis(items): return '<ul>'+''.join('<li>'+html.escape(str(x))+'</li>' for x in items)+'</ul>' if items else '<p>None</p>'
    subtitle_html=f'<p>{html.escape(subtitle)}</p>' if subtitle else ''
    closing_html=f'<p class=closing>{html.escape(closing)}</p>' if closing else ''
    source_rows=''.join(f"<tr><td>{html.escape(x.get('id',''))}</td><td>{html.escape(x.get('type',''))}</td><td>{'Yes' if x.get('enabled') else 'No'}</td><td>{'Yes' if x.get('exists') else 'No'}</td><td>{x.get('authority',0)}</td></tr>" for x in (inventory or []))
    groups_html=''.join(f"<h3>{html.escape(g['source_id'])}</h3><div class=grid>{''.join(f'<div class=card><b>{html.escape(k.replace("_"," " ).title())}</b><span>{html.escape(str(v))}</span></div>' for k,v in g['summary'].items())}</div>" for g in (groups_reports or []))
    ka=report.get('knowledge_analysis',{})
    topic_rows=''.join(f"<tr><td>{html.escape(x['topic'])}</td><td>{x['forum_messages']}</td><td>{x['help_pages']}</td><td>{html.escape('; '.join(x.get('examples',[])[:3]))}</td></tr>" for x in ka.get('top_topics',[]))
    thread_rows=''.join(f"<tr><td>{html.escape(x['subject'])}</td><td>{x['message_count']}</td><td>{x['authors']}</td><td>{html.escape(x.get('first_date','')[:10])}</td><td>{html.escape(x.get('last_date','')[:10])}</td></tr>" for x in ka.get('top_threads',[]))
    gap_rows=''.join(f"<tr><td>{html.escape(x['topic'])}</td><td>{x['forum_messages']}</td><td>{html.escape('; '.join(x.get('examples',[])[:3]))}</td></tr>" for x in ka.get('coverage_gaps',[]))
    source_intel_rows=''.join(f"<tr><td>{html.escape(x.get('name',x['source_id']))}</td><td>{x['authority']}</td><td>{x['messages']}</td><td>{x['threads']}</td><td>{x['contributors']}</td><td>{html.escape(', '.join(x.get('tags',[])))}</td></tr>" for x in ka.get('source_intelligence',[]))
    rec_rows=''.join(f"<tr><td>{x['rank']}</td><td>{html.escape(x['topic'])}</td><td>{x['forum_messages']}</td><td>{html.escape(', '.join(x.get('sources',{}).keys()))}</td><td>{x['confidence']}%</td><td>{x['impact']}</td><td>{html.escape(x['recommendation'])}</td></tr>" for x in ka.get('recommendations',[]))
    promo_rows=''.join(f"<tr><td>{html.escape(x['topic'])}</td><td>{x['forum_messages']}</td><td>{html.escape(', '.join(x.get('sources',{}).keys()))}</td><td>{x['confidence']}%</td></tr>" for x in ka.get('promotion_candidates',[]))
    analysis_html=(f"<h2>Knowledge intelligence</h2><h3>Source intelligence</h3><table><tr><th>Source</th><th>Authority</th><th>Messages</th><th>Threads</th><th>Contributors</th><th>Tags</th></tr>{source_intel_rows}</table><h3>Documentation priorities</h3><table><tr><th>Rank</th><th>Topic</th><th>Messages</th><th>Sources</th><th>Confidence</th><th>Impact</th><th>Recommendation</th></tr>{rec_rows}</table><h3>Promotion candidates</h3><table><tr><th>Topic</th><th>Messages</th><th>Sources</th><th>Confidence</th></tr>{promo_rows}</table><h3>Top forum topics</h3><table><tr><th>Topic</th><th>Forum messages</th><th>Help pages</th><th>Example discussions</th></tr>{topic_rows}</table><h3>Most active discussions</h3><table><tr><th>Discussion</th><th>Messages</th><th>Contributors</th><th>First</th><th>Last</th></tr>{thread_rows}</table><h3>Potential documentation gaps</h3><p>Frequently discussed terms with no matching Help page.</p><table><tr><th>Topic</th><th>Forum messages</th><th>Example discussions</th></tr>{gap_rows}</table>") if ka.get('enabled') else ''
    return f'''<!doctype html><meta charset=utf-8><title>{title}</title><style>body{{font:15px system-ui;margin:24px;color:#222}}h1{{margin-bottom:4px}}.grid{{display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:10px}}.card{{border:1px solid #ccc;border-radius:8px;padding:12px;display:flex;flex-direction:column}}.card span{{font-size:24px}}table{{border-collapse:collapse;width:100%}}th,td{{border:1px solid #ddd;padding:7px;text-align:left}}th{{background:#eee}}code{{background:#eee;padding:2px 4px}}.closing{{margin-top:32px;font-weight:600}}</style><h1>{title}</h1>{subtitle_html}<div class=grid>{cards}</div><h2>Knowledge sources</h2><table><tr><th>ID</th><th>Type</th><th>Enabled</th><th>Found</th><th>Authority</th></tr>{source_rows}</table>{groups_html}{analysis_html}<h2>Pages needing attention</h2><table><tr><th>Title</th><th>File</th><th>Words</th><th>Quality</th><th>Broken links</th><th>Missing images</th><th>Legacy hits</th></tr>{rows}</table><h2>Orphan pages</h2>{lis(report['orphans'])}<h2>Unused images</h2>{lis(report['unused_images'])}<h2>Duplicate titles</h2>{lis([f'{k}: {v}' for k,v in report['duplicate_titles'].items()])}{closing_html}'''

def main():
    ap=argparse.ArgumentParser(); ap.add_argument('help_zip',nargs='?'); ap.add_argument('--config',default='config.json'); ap.add_argument('--check-links',action='store_true'); a=ap.parse_args()
    cfgpath=Path(a.config).resolve(); base=cfgpath.parent; cfg=load_cfg(cfgpath)
    cfg['project']['version']=BUILDER_VERSION
    out=resolve(base,cfg['paths']['output_directory']); out.mkdir(parents=True,exist_ok=True)
    inventory=source_inventory(cfg,base); groups_reports=[]; github_reports=[]; manual_reports=[]; file_reports=[]
    report={'summary':{'topics':0,'images':0,'internal_links':0,'external_links':0,'broken_internal_links':0,'missing_anchors':0,'missing_images':0,'unused_images':0,'orphan_pages':0,'duplicate_titles':0,'legacy_references':0,'ignored_urls':0,'needs_review_urls':0,'average_words':0,'overall_quality':0},'pages':[],'orphans':[],'duplicate_titles':{},'duplicate_keywords':{},'unused_images':[]}
    hs=source(cfg,'help_zip'); hp=a.help_zip or (hs and hs.get('path'))
    if hp:
        z=resolve(base,hp)
        if not z.exists(): raise SystemExit(f'Help ZIP not found: {z}\nPlace it there, pass a ZIP argument, disable the source, or edit sources.json.')
        with tempfile.TemporaryDirectory(prefix='elmer-help-') as td:
            with zipfile.ZipFile(z) as zz: zz.extractall(td)
            root=Path(td); htmls=[p for p in list(root.rglob('*.html'))+list(root.rglob('*.htm')) if not is_archive_artifact(p.relative_to(root))]
            if htmls: root=Path(os.path.commonpath([str(p.parent) for p in htmls]))
            report=analyze(root,cfg)
            export_help_images(root,report,out/'owned-images',hs or {})
    for sc in cfg.get('sources',[]):
        if not sc.get('enabled') or sc.get('type')!='groups_io_mbox': continue
        path=resolve(base,sc.get('path',''))
        if not path.exists(): raise SystemExit(f"Enabled Groups.io MBOX not found: {path}")
        groups_reports.append(import_groups_mbox(path,sc))
    for sc in cfg.get('sources',[]):
        if not sc.get('enabled') or sc.get('type') not in ('groups_io_files','groups_io_files_zip','groups_io_files_export'): continue
        path=resolve(base,sc.get('path',''))
        if not path.exists(): raise SystemExit(f"Enabled Groups.io files export not found: {path}")
        file_reports.append(import_groups_files(path,sc))
    cache_root=resolve(base,cfg['paths'].get('connector_cache_directory','cache/connectors'))
    for sc in cfg.get('sources',[]):
        if not sc.get('enabled') or sc.get('type')!='github_repository': continue
        try: github_reports.append(load_cached_repository(cache_root/sc['id'],sc))
        except FileNotFoundError as exc: raise SystemExit(str(exc))
    for sc in cfg.get('sources',[]):
        if not sc.get('enabled') or sc.get('type')!='html_manual': continue
        try: manual_reports.append(load_cached_manual(cache_root/sc['id'],sc))
        except FileNotFoundError as exc: raise SystemExit(str(exc))
    report['sources']=inventory
    report['knowledge_analysis']=analyze_knowledge(report,groups_reports,cfg)
    report['groups_io']=[{'source_id':g['source_id'],'path':g['path'],'authority':g['authority'],'summary':g['summary']} for g in groups_reports]
    if cfg['report'].get('generate_sqlite',True): write_db(out/cfg['paths']['database_name'],report,cfg,groups_reports,github_reports+manual_reports,file_reports)
    if cfg['report'].get('generate_json',True): (out/'documentation-analysis.json').write_text(json.dumps(report,indent=2),encoding='utf-8')
    if cfg['report'].get('generate_html',True): (out/'documentation-analysis.html').write_text(html_report(report,cfg,groups_reports,inventory),encoding='utf-8')
    build={'builder':cfg['project']['builder_name'],'version':BUILDER_VERSION,'sources':inventory,'summary':report['summary'],'groups_io':[g['summary'] for g in groups_reports],'groups_io_files':[{'source_id':g['source_id'],**g['summary']} for g in file_reports],'github':[{'source_id':g['source_id'],'commit':g['manifest']['commit'],'counts':g['counts']} for g in github_reports],'manuals':[{'source_id':g['source_id'],'version':g['manifest']['version'],'sections':len(g['documents'])} for g in manual_reports]}
    history_path=out/'build-history.json'
    try: history=json.loads(history_path.read_text(encoding='utf-8')) if history_path.exists() else []
    except Exception: history=[]
    history.append({'built_at':datetime.now(timezone.utc).isoformat(),'version':BUILDER_VERSION,'summary':report['summary'],'groups_io':[{'source_id':g['source_id'],**g['summary']} for g in groups_reports],'groups_io_files':[{'source_id':g['source_id'],**g['summary']} for g in file_reports],'github':[{'source_id':g['source_id'],'commit':g['manifest']['commit'],'counts':g['counts']} for g in github_reports],'manuals':[{'source_id':g['source_id'],'version':g['manifest']['version'],'sections':len(g['documents'])} for g in manual_reports],'recommendations':report.get('knowledge_analysis',{}).get('recommendations',[])[:10]})
    history_path.write_text(json.dumps(history[-100:],indent=2),encoding='utf-8')
    if cfg['report'].get('generate_build_report',True): (out/'build-report.json').write_text(json.dumps(build,indent=2),encoding='utf-8')
    s=report['summary']; print(f"{cfg['project']['builder_name']} v{cfg['project']['version']}")
    status=format_message(cfg.get('messages',{}).get('build_complete',''),cfg,s); closing=format_message(cfg.get('messages',{}).get('console_closing',''),cfg,s)
    if status: print(status)
    if s.get('approved_images') is not None:
        print(f"Approved Help images: {s['approved_images']}")
    for g in groups_reports:
        x=g['summary']; print(f"Groups.io: {x['messages']} messages, {x['threads']} threads, {x['contributors']} contributors")
    for g in github_reports:
        print(f"GitHub {g['name']}: {len(g['documents'])} documents at {g['manifest']['commit'][:12]}")
    for g in manual_reports:
        print(f"Manual {g['name']}: {len(g['documents'])} sections for version {g['manifest']['version']}")
    for g in file_reports:
        x=g['summary']; print(f"Groups.io files: {x['documents']} documents, {x['duplicates']} duplicates, {x['extraction_failed_or_short']} failed or short")
    if closing: print(closing)
if __name__=='__main__': main()
