pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["./accounts.html","RigPi Introduction &#62; Accounts","RigPi accommodates up to four or more user accounts. Each account must have a unique username and can control one radio. Accounts can have the sam...",""],
["./accounts2.html","Settings &#62; Account","Account Management RigPi supports multiple user accounts with different access levels. This page covers account requests, approval, settings, and ...",""],
["./acknowlegements.html","RigPi Introduction &#62; Acknowlegements","The RigPi 5 project would not have been possible without the help of many. The following are especially thanked for their help with coding, testin...",""],
["./advanced-radio.html","Settings &#62; Advanced Radio","Two Radio Settings options are provided in the RigPi SETTINGS Menu. Basic Radio settings take advantage of Hamlib default settings for each radio....",""],
["./alsamixer.html","Other Programs &#62; Alsamixer","RigPi Audio doesn&#39;t have settings of its own, but a Linux utility named Alsamixer is included with RSS for that purpose. You can also use the Audi...",""],
["./ask-elmer.html","Views &#62; Ask Elmer","Ask Elmer is RigPi’s built-in help assistant for questions about RigPi and amateur radio. It can answer using Official RigPi Help, RigPi and Hamli...",""],
["./band-filter.html","Settings &#62; Band Filter","The Band Filter settings window provides a way to disable band selections in the Tuner and Keyer windows.  For example, a KX3 with a 2-meter ...",""],
["./calendar.html","Views &#62; Calendar","RigPi Calendar is the calendar display for RigPi users. Set up events for Calendar in the Scheduler settings window.  Calendar events include...",""],
["./chapter-2.html","Other Programs","Additional Ham Radio Software Additional amateur radio software provided with RigPi Station Server is available from the Raspberry Pi Desktop. Sel...",""],
["./claws-mail.html","Other Programs &#62; Claws Mail","Claws Mail is a light-weight email client providing a way to send and receive email.  Claws Mail is not installed by default.",""],
["./cloudflare.html","Other Programs &#62; Cloudflare","Cloudflare Tunnel provides secure remote access to RigPi and ELMER SDR from anywhere in the world — without opening ports in your router or config...",""],
["./connecting-programs.html","Other Programs &#62; Connecting to RSS from External Programs","RSS combined with popular logging programs provides another layer of flexibility. The screen shot below shows RSS, CommCat (no longer published) a...",""],
["./contour-shuttlexpress.html","Other Programs &#62; Contour ShuttleXpress","The Contour ShuttleXpress provides a convenient way to adjust the RigPi frequency and control PTT using a Windows or Mac computer through a USB po...",""],
["./definitions.html","Technical &#62; Glossary","Term Definition ARRL The American Radio Relay League (ARRL) is a worldwide organization of amateur radio operators with its headquarters in Newing...",""],
["./elmer.html","Views &#62; Elmer","The ELMER tab opens a full-window RigPi-SDR workspace. Use it when you want more room for the spectrum, waterfall and SDR controls.",""],
["./external-accounts.html","Settings &#62; Account &#62; External Accounts","RigPi SDR works with several optional third-party services that extend its capabilities. Each service requires a free or low-cost account. This pa...",""],
["./fail2ban.html","Other Programs &#62; Fail2Ban","Fail2ban, included with RigPi is an open-source intrusion prevention software that helps protect Linux-based systems from malicious attacks by mon...",""],
["./fan-control.html","Other Programs &#62; Fan Control","RigPi supports automatic, temperature-controlled cooling through the K1EL RigPi Keyer board on Raspberry Pi 4. The Raspberry Pi 5 has its own dedi...",""],
["./flarq.html","Other Programs &#62; Flarq","FLARQ, also known as Fast Light Automatic Repeat reQuest, is a software utility that works in conjunction with the Fldigi application. FLARQ is de...",""],
["./fldigi.html","Other Programs &#62; Fldigi","Fldigi is a popular open-source software application designed for amateur radio digital communications. It stands for \"Fast Light Digital mod...",""],
["./flic-switch.html","Other Programs &#62; Flic Switch and iOS Shortcuts","Flic is a remote control switch that uses Bluetooth for communicating with phones, tablets, and Mac computers. For purchase a Flic or more informa...",""],
["./grid-tracker.html","Other Programs &#62; Grid Tracker","Grid Tracker is a Swiss Army Knife for WSJT-X.  Start WSJT-X from the Ham Radio menu, then start Grid Tracker.  No configuration setting...",""],
["./installing-the-latest-hamlib.html","Technical &#62; Installing the latest Hamlib","The Hamlib control library is constantly updated by the maintenance team.  Hamlib must be updated in RigPi manually using these steps:",""],
["./internet-service.html","RSS Connections &#62; Internet Connections","RSS is designed to operate without Internet access. This feature makes it convenient when taking RSS away from your home for portable or mobile op...",""],
["./introduction.html","RigPi Introduction","RigPi&#8482; Station Server v 5.0     RigPi Station Server   RigPi (RSS: RigPi Station Server) is a remote control system for amateur rad...",""],
["./js8call.html","Other Programs &#62; JS8Call","JS8Call is a derivative of the WSJT-X application, structured and redesigned for message passing.  It is not supported by, nor endorsed by, t...",""],
["./k1el-rigpi-keyer-and-box.html","RSS Connections &#62; K1EL RigPi Keyer and Box","The K1EL RigPi Keyer is software-compatible with the MFJ Keyer board, but is physically different. The K1EL RigPi Keyer board supports a fan for c...",""],
["./keyer.html","Views &#62; Keyer","1: Sent CW   Displays CW already sent to transmitter.   Clear the sent data by clicking/tapping CLEAR LEFT.  In HOLD mode, use back...",""],
["./keyer2.html","Settings &#62; Keyer","The CW Keyer Settings window is used for the RigPi Keyer, or external K1EL WinKeyer. These settings do not affect keying via CAT except for Speed....",""],
["./libreoffice.html","Other Programs &#62; LibreOffice","LibreOffice is a suite of programs you can use for office tasks.  The programs include:",""],
["./log-designer.html","Settings &#62; Log Designer","The Log Designer provides a drag-and-drop way to modify existing log styles, or to design new ones. A log style is assigned to each log, but you c...",""],
["./log-editor.html","Views &#62; Log &#62; Log &#62; Log Editor","Use the Log Editor to add new or edit existing contacts. The Log Editor is opened by clicking an Edit button on the Log window, or by clicking the...",""],
["./log.html","Views &#62; Log","1: Navigating   Use the Log navigation bar at the top left of the log under the RSS navigation bar to move from page-to-page. Up to 25 QSOs a...",""],
["./macros.html","Settings &#62; Macros","RSS provides 128 programmable macro keys in 4 banks of 32 each. The keys are available in the Tuner and CW Keyer windows. Each macro has a space t...",""],
["./message-aggregator.html","Other Programs &#62; Message Aggregator","Message Aggregator implements the server side of the message protocol used by WSJT-X. WSJT-X is a client of the protocol. Message Aggregator is no...",""],
["./mode-filter.html","Settings &#62; Mode Filter","The Mode Filter settings window provides a way to disable mode selections in the Tuner and Keyer windows.  For example, you may not want to u...",""],
["./motion.html","Other Programs &#62; Motion (Video)","Motion is an application for creating streaming video.  Motion is installed and configured on RigPi.  The primary use for RigPi video is...",""],
["./mumble-autostart.html","Other Programs &#62; Mumble Autostart","RigPi 5 users: Mumble and Mumble Autostart are no longer used for normal RigPi station audio. Current receive and transmit audio runs directly in ...",""],
["./mumble.html","Other Programs &#62; Mumble","RigPi 5 users: Mumble and Plumble are no longer used for normal RigPi station audio. Current receive and transmit audio runs directly in the brows...",""],
["./overview.html","Other Programs &#62; Overview","Additional ham radio programs are installed on RSS. The Other Programs topic provides information that relates to RSS and the program. For complet...",""],
["./panadaptor.html","Other Programs &#62; Panadapter","RigPi-SDR now has its own Panadaptor, including a Spectrum and Waterfall View.  The following is included for older RigPi versions.",""],
["./panels.html","Technical &#62; Panels","The Graphics User Interface (GUI) used in the RSS Tuner window is based on a commercial product \"Perfect Widgets\" by Perpetuum Software....",""],
["./passwords.html","RigPi Introduction &#62; Passwords","Using custom passwords is critical to the security of your RSS if you intend to connect to and control your station through the Internet. There ar...",""],
["./programming-code.html","Technical &#62; Programming","The following languages and tools were used in the development of RigPi.",""],
["./radio-control.html","RSS Connections &#62; Radio Control","RigPi controls each radio through one of the four USB connectors on the Raspberry Pi.  If your radio has a classic serial port, a serial-to-U...",""],
["./radio.html","Settings &#62; Basic Radio","Two Radio Settings options are provided in the RigPi SETTINGS Menu. Basic Radio settings take advantage of the Hamlib default settings for each ra...",""],
["./raspberri-pi-settings.html","Technical &#62; Raspberry Pi Settings","You may wish to change many Raspberry Pi settings such as screen resolution.  Here is how to proceed:",""],
["./raspberry-pi-desktop.html","RigPi Introduction &#62; Raspberry Pi Desktop","Raspberry Pi 5 Desktop (VNC)  The Raspberry Pi Desktop is similar to many graphics desktops. The Raspberry Menu button on the left end of the...",""],
["./rebooting-rigpi.html","Technical &#62; Rebooting RigPi","Occasionally it is necessary to reboot RigPi.  There are several ways to proceed.",""],
["./relay-switching.html","Other Programs &#62; Relay Switching","The Sainsmart 8-channel 12V Relay Module is compatible with RigPi.  It is controlled from one of the Raspberry Pi USB ports using a standard ...",""],
["./remote-connections.html","RSS Connections &#62; Remote Connections","Internet Access to your Raspberry Pi   RigPi has a new secure connection path through Cloudflare or DuckDNS.  DuckDNS requires a port to...",""],
["./remote-support.html","Settings &#62; Account &#62; Temporary Remote Support","Temporary Remote Support lets a trusted RigPi support technician diagnose a station without exposing SSH port 22 or asking the station owner to co...",""],
["./rempote-operations.html","RigPi Introduction &#62; Remote Operations: Legal Concerns","You can connect to RigPi from any location where the Internet is available.  Remote operations are permitted in the United States, but not al...",""],
["./resetting-rigpi-access.html","Technical &#62; Factory Reset","Factory Reset returns the RigPi station database, accounts, saved station settings, and protected remote-service connections to factory condition....",""],
["./rigpi-audio-update.html","Technical &#62; RigPi Audio Update","RigPi 5 users: This is a legacy hardware topic. Current RigPi receive and transmit audio runs directly in the browser. See RigPi-SDR Audio for cur...",""],
["./rigpi-audio.html","RSS Connections &#62; RigPi Audio","Current RigPi receive and transmit audio runs directly between RigPi and a modern web browser. The same Audio panel is available in the full ELMER...",""],
["./rigpi-keyer-ptt.html","Technical &#62; RigPi Keyer PTT","The WinKeyer IC used for CW keying has an independent PTT capability that can control the PTT output from RigPi Keyer. This special Keyer PTT oper...",""],
["./rigpi-keyer.html","RSS Connections &#62; RigPi Keyer","RigPi Keyer is a versatile Morse code generator based on the popular K1EL WinKeyer3 IC. It connects to the Raspberry Pi through the GPIO header an...",""],
["./rigpi-lite.html","Views &#62; RigPi Lite","RigPi Lite provides a low cpu-utilization connection for other programs that use Hamlib to control radios and rotors such as WSJT-X and Fldigi.",""],
["./rigpi-login-code.html","Technical &#62; RigPi Login Code","RigPi requires a unique username for each account.  Passwords are optional, but are recommended if you wish to use RigPi through the Internet...",""],
["./rigpi-remote-keyer.html","Technical &#62; RigPi Remote Keyer","See also: Keyer Advanced Radio   The RigPi Remote Keyer feature allows you to operate CW from a remote location using a paddle, bug or straig...",""],
["./rigpi-sdr.html","Views &#62; RigPi-SDR","RigPi-SDR Tuned to Local FM Station   RigPi-SDR: Software Defined Radio for RigPi RigPi-SDR is an integrated software defined radio applicati...",""],
["./rigpi-sdr2.html","Technical &#62; RigPi Elmer-SDR","RigPi 5 Software Defined Radio Architecture  System Architecture ELMER runs as a Python/Flask web server on the Raspberry Pi 5, integrated wi...",""],
["./rigpi_local-on-windows-compute.html","Technical &#62; Rigpi5.local on Windows computers","The domain rigpi5.local can be used as an easy way to connect to RigPi using a browser on another computer.  Many operating systems automatic...",""],
["./rotor-control.html","RSS Connections &#62; Rotor Control","Important   RigPi uses your location and the location of a remote station to predict the correct bearing.  You must enter your location&#39;...",""],
["./rotor.html","Settings &#62; Rotor","One rotor can be assigned to and controlled through each account. 30 Rotor models are supported by Hamlib from 21 manufacturers. The screen shot s...",""],
["./rss-connections.html","RSS Connections","The Raspberry Pi provides a number of connections. Here is a list:",""],
["./rss-on-mobile-deviices_2.html","RigPi Introduction &#62; RSS on Mobile Devices","RigPi can be used on any mobile device using an Internet browser. Since RigPi uses a browser, no app is required. Station control and audio are pr...",""],
["./rss-updater.html","Other Programs &#62; Update RSS Files","Updating the files for RSS is done automatically when a new minor version is detected, or manually from the SETTINGS&#62;System menu.  Updates...",""],
["./scematics.html","Technical &#62; Schematics","Schematics and additional information for the K1EL Winkeyer 2 are here.",""],
["./scheduler.html","Settings &#62; Scheduler","RigPi Scheduler is the settings window for RigPi Calendar.  Scheduler provides a way to add events to Calendar for any day of the year. &#38;nbsp...",""],
["./sdr-4.html","Views &#62; SDR 4","SDR4 is the administrator&#39;s SDR dashboard. It displays up to four account SDR workspaces together, so you can view multiple configured receivers f...",""],
["./second-topic.html","RigPi Introduction &#62; Quick Start Guide","What is Needed 1. RigPi Station Server (RSS) a. Raspberry Pi 4B+ or Raspberry Pi 5 (recommended) b .5.1-volt, 3-amp Power Supply with a  USB-...",""],
["./security.html","RigPi Introduction &#62; Security","Security RigPi controls station equipment and can transmit when an account has permission. Treat it like any other Internet-connected station cont...",""],
["./set-up-elmer.html","Settings &#62; Account &#62; Set Up Ask Elmer, Elmer Voice and Elmer Control","Elmer adds three related capabilities to RigPi:  Feature Purpose Ask Elmer Answers RigPi and amateur-radio questions using an indexed technic...",""],
["./settings.html","Settings","RSS is customized using settings windows. The settings, except for System, are unique for each account.",""],
["./sharing-radios.html","Technical &#62; Sharing Radios, Rotors and Keyers","Radio   RSS allows multiple radios to be connected, controlled and shared. Each radio is connected through a unique USB port on the Raspberry...",""],
["./slider-overrides.html","Settings &#62; Slider Overrides","Depending on the capabilities of your radio, up to four sliders are shown on the Tuner window.  The Slider Override settings can be used to s...",""],
["./spots.html","Views &#62; Spots","The RigPi spots shows DX spots provided by one of a large number of DX Cluster Telnet sites. The site you wish to use is selected in SETTINGS&#62;S...",""],
["./spots2.html","Settings &#62; Spots","The Spots function connects to a Telnet spot cluster using your callsign.  Enter your callsign in SETTINGS&#62;Accounts&#62;Account Editor.",""],
["./supported-radio-features.html","Technical &#62; Supported Radio Features","Hamlib supports over 200 radios. Not all controllable features are supported. Custom macros can be created using Hamlib commands, but only if that...",""],
["./system.html","Settings &#62; System","System Settings System Settings provides information about system aspects of RSS and buttons to reboot RigPi or shut it down. System Settings is o...",""],
["./system2.html","Technical &#62; System","Swap Space   Swap space is memory used when the system runs out of RAM.  Usually the Linux Swap Space is not used in RSS. Many programs ...",""],
["./technical.html","Technical","Information about technical aspects of RSS are contained in this section.",""],
["./troubleshooting.html","Technical &#62; Troubleshooting","Radio won&#39;t connect   The first thing to try is Ask Elmer.  Elmer will analyze your radio connection and providde suggestions.  Whe...",""],
["./trustedqsl.html","Other Programs &#62; TrustedQSL","Open source libraries and utilities to support using digital signatures for Amateur radio QSL information. It can be used to digitally sign and up...",""],
["./tuner.html","Views &#62; Tuner","SDR: Top, Center, Bottom   1: Navigation Bar   Navigate to https://www.rigpi.net by clicking the RigPi logo or RigPi name.  TUNER.....",""],
["./ufw-firewall.html","Other Programs &#62; UFW Firewall","The UFW firewall is included with RigPi as an added security measure.  It can be enabled or disabled using Terminal.",""],
["./universal-functions.html","RigPi Introduction &#62; Universal Functions","Each RigPi window has functions that are present on all RigPi windows.",""],
["./users.html","Settings &#62; Account &#62; Account Editor","The Account Settings window shows a list of all RSS accounts. When you start RSS the first time, a single account named admin with callsign ADMIN ...",""],
["./using-a-dynamic-dns-service.html","RSS Connections &#62; Using a Dynamic DNS Service","Your Internet IP can change from time-to-time, especially if you reboot your Internet modem. If you are away when this happens, you won&#39;t be able ...",""],
["./views.html","Views","A view is a web page viewed through any browser. Each view has common elements, a navigation bar at the top and a status bar at the bottom.",""],
["./web.html","Views &#62; Web","Web page for W1AW obtained from FCC data    Web page for W1AW obtained from QRZ XML data   Callbook data for the Web page is obtain...",""],
["./welcome-topic.html","RigPi Introduction &#62; Welcome to RSS","Welcome to RigPi Station Server!   RigPi Station Server (RSS) is an easy-to-use multi-operator, multi-radio (MOMR) amateur radio control, log...",""],
["./whats-new.html","RigPi Introduction &#62; What&#39;s New","RigPi 5.0 Changes 10/1/2026 RigPi 5.0 highlights Ask Elmer answers questions about RigPi, operating frequencies, stations, clubs, callbook informa...",""],
["./wsjt-x.html","Other Programs &#62; WSJT-X","RigPi has its own FT8 and FT4 decoding, so WSJT-X is not required to monitor FT8/FT4 traffic.  Open FT8 in the SDR panel.  WSJT-X is req...",""]];
